main/urls.py
from django.urls import path
from . import views
from .models import Settings

urlpatterns = [
    path('', views.index, name = 'index'),
    path('index/', views.index, name = 'index'),
    path('video/', views.video_stream, name = 'video'),
    path('record/', views.video_record_current, name = 'record'),
    path('logs/', views.logs, name = 'logs'),
    path('delete_log/<log_id>/', views.delete_log, name = "delete_log"),
    path('delete_log_confirm/<log_id>', views.delete_log_confirm, name = 'delete_log_confirm'),
    path('settings/', views.settings, name = 'settings'),
    path('settings_save/', views.settings_save, name = 'settings_save'),
    path('watch_video/<log_id>/', views.watch_video, name = 'watch_video'),
]

user_authentication/urls.py
from django import urls
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'),
         name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'),
    path('signup/', views.signup, name = 'signup'),
]

video_door/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns

urlpatterns = [
path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace = 'main')),
    path('user_authentication/', include(('user_authentication.urls',
                                     'user_authentication'),
                                    namespace = 'user_authentication')),
]

urlpatterns +=staticfiles_urlpatterns()

user_authentication/models.py
from django.db import models

user_authentication/forms.py
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class ModifiedUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

user_authentication/views.py
from django.shortcuts import render, redirect
from .forms import ModifiedUserCreationForm

def signup(request):
    if request.method == 'POST':
        form = ModifiedUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
        username = form.cleaned_data.get('username')
        print('***********', username,'*********')
        return render(request, 'signup_confirmation.html',
                      {'username': username})
    else:
        form = ModifiedUserCreationForm
        return render(request, 'signup.html', {'form' : form})

templates/user_authentication/login.html
{% extends 'base.html'%}

{%block title%}
Login
{% endblock%}

{% block content%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
      <center>
    <h1 class="display-4">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-lock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.5 9a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V9z"/>
  <path fill-rule="evenodd" d="M4.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z"/>
</svg>
        Login
    </h1>
      <br>
    <p class="lead">
        <form action = "#" method = "POST">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input type = "submit" value = "Login">
    </form>
    </p>
          <br>
      <a href = "{% url 'user_authentication:signup' %}">
          Don't have an account? Click here to signup.
      </a>
      </center>
  </div>
</div>

{% endblock %}

templates/user_authentication/logout.html
{% extends 'base.html'%}

{% block title %}
Logout
{% endblock%}

{% block content%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-lock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.5 9a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V9z"/>
  <path fill-rule="evenodd" d="M4.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z"/>
</svg>
        You have successfully logged out.
    </h1>
<br>
<a href = "{% url 'user_authentication:login' %}">
    Click here to login again.
</a>
  </div>
</div>

{% endblock %}

templates/user_authentication/signup.html
{% extends 'base.html'%}

{% block title%}
    Signup
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-lock-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.5 9a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V9z"/>
  <path fill-rule="evenodd" d="M4.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z"/>
</svg>
        Create Account
    </h1>
      <br>
    <p class="lead">
   <form action = "#" method = "POST">
    {% csrf_token %}
    {{ form.as_p}}
    <br>
    <input type = "submit" value = "Signup">
</form>
      <br>
      <a href = "{% url 'user_authentication:login' %}">
          Already have an account? Click here to signin.
      </a>
    </p>
  </div>
</div>

{% endblock %}

templates/user_authentication/signup_confirmation.html
{% extends 'base.html'%}

{% block title %}
Signup Complete
{% endblock %}

{% block content%}
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
    Congratulations! You have successfully signed up.
    </h1>
      <h2>Hello! {{username}}</h2>
    <p>
        <a href = "{% url 'user_authentication:login' %}">
            Click here to login.
        </a>
    </p>
  </div>
</div>

{% endblock %}