main/urls.py
from django.urls import path
from . import views
from .models import Settings

urlpatterns = [
    path('', views.index, name = 'index'),
    path('index/', views.index, name = 'index'),
    path('video/', views.video_stream, name = 'video'),
    path('record/', views.video_record_current, name = 'record'),
    path('logs/', views.logs, name = 'logs'),
    path('delete_log/<log_id>/', views.delete_log, name = "delete_log"),
    path('delete_log_confirm/<log_id>', views.delete_log_confirm, name = 'delete_log_confirm'),
    path('settings/', views.settings, name = 'settings'),
    path('settings_save/', views.settings_save, name = 'settings_save'),
    path('watch_video/<log_id>/', views.watch_video, name = 'watch_video'),
]

user_authentication/urls.py
from django import urls
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'),
         name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'),
    path('signup/', views.signup, name = 'signup'),
]

video_door/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns

urlpatterns = [
path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace = 'main')),
    path('user_authentication/', include(('user_authentication.urls',
                                     'user_authentication'),
                                    namespace = 'user_authentication')),
]

urlpatterns +=staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.contrib.auth.forms import User
from django.core.validators import MinValueValidator, MaxValueValidator
import time
import datetime

class Records(models.Model):
    user =  models.ForeignKey(User, on_delete = models.CASCADE)
    datetime = models.DateTimeField(default = datetime.datetime.now())
    recording = models.BooleanField(default = False)
    continued = models.BooleanField(default = False)
    relative_path = models.CharField(max_length = 30, null = True)

class Settings(models.Model):
    recording = models.BooleanField()
    path = models.CharField(max_length=200, null = True)
    fps = models.PositiveIntegerField(validators=[MinValueValidator(5),
                                         MaxValueValidator(30)])

main/forms.py
from .models import Settings
from django import forms

class Settings_Form(forms.ModelForm):
    class Meta:
        model = Settings
        fields = ['path', 'recording', 'fps']
        if Settings.objects.get(pk = 1).recording == True:
            widgets = {
            'path' : forms.TextInput(
                attrs = {'value' : Settings.objects.get(pk =1).path}),
            'recording' : forms.CheckboxInput(
                attrs = {'checked' : "on"}),
            'fps' : forms.TextInput(
                attrs = {'Value' : Settings.objects.get(pk = 1).fps,
                         'class' : 'vIntegerField',
                         'type' : 'number',
                         'min' : "5",
                         'max' : "30"})
            }
        else:
            widgets = {
                'path': forms.TextInput(
                    attrs={'value': Settings.objects.get(pk=1).path}),
                'fps': forms.TextInput(
                    attrs={'Value': Settings.objects.get(pk=1).fps,
                           'class': 'vIntegerField',
                           'type': 'number',
                           'min': "5",
                           'max': "30"})
            }

        # def recording_status(self):
        #     if Settings.objects.get(pk=1).recording == True:
        #         return "yes"
        #     else:
        #         return "false"

main/views.py
import sys
sys.path.append('../')
from django.http import HttpResponse, HttpResponseServerError
from django.http.response import StreamingHttpResponse
from camera.capture_video import Live_Stream, gen
from django.shortcuts import redirect, render
from django.views.decorators import gzip
from django.contrib import messages
from .models import Records, Settings
from .forms import Settings_Form
from django.contrib.auth.decorators import login_required
import datetime
import os

@login_required
def index(request):
    if request.method == 'POST':
        pass
    else:
        settings = Settings.objects.get(pk = 1)
        file = open('recording_switch.txt', 'r')
        file_data = file.read()
        file.close()
        if file_data == 'True-Current':
            file_data = True
        else:
            file_data = False
        return render(request, 'index.html',
                      {'settings' : settings,
                        'recording_current' : file_data})

def watch_video(request, log_id = ""):
    if request.method == 'POST':
        pass
    else:
        return render(request, 'watch_video.html',
                      {'watch_video_path' : Settings.objects.get(pk = 1).path + Records.objects.get(pk = log_id).relative_path})

def logs(request):
    if request.method == "POST":
        print('logs post block reached....')
        logs_filter = Records.objects.filter(
            datetime__range = [request.POST.get('date_range_start'),
                               request.POST.get('date_range_stop')]
        )
        print('date filtering done....')
        print(logs_filter)
        path = Settings.objects.get(pk=1).path
        return render(request, 'logs.html', {'logs': logs_filter,
                                             'path': path})
    else:
        logs = Records.objects.all()
        path = Settings.objects.get(pk = 1).path
        return render(request, 'logs.html', {'logs' : logs,
                                             'path' : path})

def delete_log_confirm(request, log_id):
    if request.method == 'POST':
        return redirect('main:delete_log', log_id)
    else:
        return render(request, 'delete_log_confirm.html',
                      {'log_id' : log_id})

def delete_log(request, log_id):
    record = Records.objects.get(id = log_id)
    path = Settings.objects.get(pk = 1).path + record.relative_path
    if os.path.exists(str(path)):
        os.remove(str(path))
    else:
        pass
    record.delete()
    messages.success(request, 'Successfully deleted the selected log....')
    return redirect('main:logs')

def settings(request):
    if request.method == "POST":
        print('POST request accepted....')
        form = Settings_Form(request.POST)
        print('form loaded....')
        if form.is_valid():
            new = Settings.objects.get(pk=1)
            if form.cleaned_data.get('path') == 'static/media' or form.cleaned_data.get('path') == 'static/media/':
                new.path = 'static/media'
            else:
                new.path = 'static/media' + form.cleaned_data.get('path')
            new.recording = form.cleaned_data.get('recording')
            new.fps = form.cleaned_data.get('fps')
            new.save()
        return redirect('main:settings_save')
    else:
        existing_data = Settings.objects.get(pk = 1)
        return render(request, 'settings.html',
                      {'form' : Settings_Form})
def settings_save(request):
    return render(request, 'settings_save.html', {})

@gzip.gzip_page
def video_stream(request):
    print('index block reached....')
    file = open('recording_switch.txt', 'r')
    file_data = file.read()
    file.close()
    print('**** file_data = ', file_data)
    if file_data == 'True-Current':
        obj = Records.objects.last()
        obj.continued = True
        obj.save()
    elif Settings.objects.get(pk=1).recording == True:
        obj = Records.objects.create(user=request.user,
                                     recording=True,
                                     datetime=datetime.datetime.now())
        obj.save()
    else:
        print('else block entered....')

        obj = Records.objects.create(user=request.user,
                                     datetime=datetime.datetime.now())
        print('object created successfully....')
        obj.save()
        print('object saved successfully....')
    print('just before return....')
    try:
        return StreamingHttpResponse(gen(Live_Stream()),content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        print("aborted")

@login_required()
def video_record_current(request):
    file = open('recording_switch.txt', 'w')
    file.write('True-Current')
    file.close()
    return redirect('main:index')

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>
        {% block title%}

        {% endblock%}
    </title>
  </head>

<body>
<div class = "container-fluid">

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'main:index' %}">USS Video Door</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'main:index' %}">Stream <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:logs' %}">Logs</a>
      </li>
    </ul>
  </div>

        <ul class="navbar-nav mr-auto float-right">
          {% if user.is_authenticated %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.username }}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'main:settings' %}">Settings</a>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'user_authentication:logout' %}">Logout</a>
        </div>
      </li>
          {% else %}
              <li class="nav-item">
        <a class="nav-link" href = "{% url 'user_authentication:login' %}">Login</a>
      </li>
          {% endif %}
</ul>
</nav>



<div class = "container">
    {% block content %}

    {% endblock %}
</div>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


  </div>
  </body>
</html>

templates/main/index.html
{% extends "base.html"%}

{% block title %}
Stream
{% endblock %}

{% block content %}
    <center>
<p>
    <p>
    <center>
<img src = "{% url 'main:video' %}" style="overflow:hidden;">
<!--There should not be any gap between main:video-->
    </center>
</p>
</div>
<br>

<center>
{% if settings %}
  {% if settings.recording %}
<h1>
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera-reels-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.667 6h6.666C10.253 6 11 6.746 11 7.667v6.666c0 .92-.746 1.667-1.667 1.667H2.667C1.747 16 1 15.254 1 14.333V7.667C1 6.747 1.746 6 2.667 6z"/>
  <path d="M7.404 11.697l6.363 3.692c.54.313 1.233-.066 1.233-.697V7.308c0-.63-.693-1.01-1.233-.696l-6.363 3.692a.802.802 0 0 0 0 1.393z"/>
  <circle cx="3" cy="3" r="3"/>
  <circle cx="9" cy="3" r="3"/>
</svg>
</h1>
{% elif recording_current %}
<h1>
        <a href = "{% url 'main:index' %}">
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera-video-off" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M1.075 3.196A2.159 2.159 0 0 0 .5 4.666v6.667c0 1.197.97 2.167 2.167 2.167h6.666c.568 0 1.084-.218 1.47-.575l-.708-.708c-.204.176-.47.283-.762.283H2.667A1.167 1.167 0 0 1 1.5 11.333V4.667c0-.292.107-.558.283-.762l-.708-.709zM10.5 8.379V4.667c0-.645-.522-1.167-1.167-1.167H5.621l-1-1h4.712c1.094 0 1.998.81 2.146 1.862l2.037-1.182c.859-.498 1.984.095 1.984 1.128v7.384c0 .482-.245.869-.594 1.093l-.79-.79a.317.317 0 0 0 .384-.303V4.308a.318.318 0 0 0-.482-.263L11.5 5.505V9.38l-1-1z"/>
  <path fill-rule="evenodd" d="M13.646 14.354l-12-12 .708-.708 12 12-.708.707z"/>
</svg>
          </a>
</h1>
{% else %}
<h1>
    <a href = "{% url 'main:record' %}">
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera-video" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M2.667 3.5c-.645 0-1.167.522-1.167 1.167v6.666c0 .645.522 1.167 1.167 1.167h6.666c.645 0 1.167-.522 1.167-1.167V4.667c0-.645-.522-1.167-1.167-1.167H2.667zM.5 4.667C.5 3.47 1.47 2.5 2.667 2.5h6.666c1.197 0 2.167.97 2.167 2.167v6.666c0 1.197-.97 2.167-2.167 2.167H2.667A2.167 2.167 0 0 1 .5 11.333V4.667z"/>
  <path fill-rule="evenodd" d="M11.25 5.65l2.768-1.605a.318.318 0 0 1 .482.263v7.384c0 .228-.26.393-.482.264l-2.767-1.605-.502.865 2.767 1.605c.859.498 1.984-.095 1.984-1.129V4.308c0-1.033-1.125-1.626-1.984-1.128L10.75 4.785l.502.865z"/>
</svg>
          </a>
</h1>
{% endif %}
{% else %}
<h3>Settings not available.</h3>
{% endif %}
</center>
    </center>

{% endblock %}

templates/main/logs.html
{% extends 'base.html'%}
{% load static %}

{%block title%}
Logs
{%endblock%}

{% block content %}
<div class="jumbotron jumbotron-fluid">

  <div class="container">

    <h1 class="display-4">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
  <path fill-rule="evenodd" d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
</svg>
      Logs
    </h1>
<br>
      <br>

  {% if logs %}

            <form action="{% url 'main:logs' %}" method = "POST">
                {% csrf_token %}
  <label for="birthday">Filter your logs by date : </label>
  <input type="date"  name="date_range_start">
                -
                <input type="date"  name="date_range_stop">

  <input type="submit">
</form>

<br>
      <br>


      <table class="table  table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope = "col">ID</th>
      <th scope="col">Date</th>
        <th scope = "col">User</th>
      <th scope="col">View / Download</th>
        <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for log in logs reversed %}
  <tr>
      <td>{{ log.id }}</td>
      <td>{{ log.datetime }}</td>
      <td>{{ log.user.username }}</td>
      <td>
          {% if log.recording or log.continued %}
          <a href = "{% url 'main:watch_video' log.id %}">
          <svg  width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-binoculars" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M3 2.5A1.5 1.5 0 0 1 4.5 1h1A1.5 1.5 0 0 1 7 2.5V5h2V2.5A1.5 1.5 0 0 1 10.5 1h1A1.5 1.5 0 0 1 13 2.5v2.382a.5.5 0 0 0 .276.447l.895.447A1.5 1.5 0 0 1 15 7.118V14.5a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 14.5v-3a.5.5 0 0 1 .146-.354l.854-.853V9.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v.793l.854.853A.5.5 0 0 1 7 11.5v3A1.5 1.5 0 0 1 5.5 16h-3A1.5 1.5 0 0 1 1 14.5V7.118a1.5 1.5 0 0 1 .83-1.342l.894-.447A.5.5 0 0 0 3 4.882V2.5zM4.5 2a.5.5 0 0 0-.5.5V3h2v-.5a.5.5 0 0 0-.5-.5h-1zM6 4H4v.882a1.5 1.5 0 0 1-.83 1.342l-.894.447A.5.5 0 0 0 2 7.118V13h4v-1.293l-.854-.853A.5.5 0 0 1 5 10.5v-1A1.5 1.5 0 0 1 6.5 8h3A1.5 1.5 0 0 1 11 9.5v1a.5.5 0 0 1-.146.354l-.854.853V13h4V7.118a.5.5 0 0 0-.276-.447l-.895-.447A1.5 1.5 0 0 1 12 4.882V4h-2v1.5a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V4zm4-1h2v-.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5V3zm4 11h-4v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14zm-8 0H2v.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5V14z"/>
</svg>
          </a>
          &nbsp / &nbsp
          <a href = "/{{ path }}{{ log.relative_path }}" download>
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-download" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M.5 8a.5.5 0 0 1 .5.5V12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.5a.5.5 0 0 1 1 0V12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8.5A.5.5 0 0 1 .5 8z"/>
  <path fill-rule="evenodd" d="M5 7.5a.5.5 0 0 1 .707 0L8 9.793 10.293 7.5a.5.5 0 1 1 .707.707l-2.646 2.647a.5.5 0 0 1-.708 0L5 8.207A.5.5 0 0 1 5 7.5z"/>
  <path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0v-8A.5.5 0 0 1 8 1z"/>
</svg>
          </a>
      {% if log.continued %}
      &nbsp
      (Delayed)
        {% endif %}

          {% else %}
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
</svg>
          {% endif %}
      </td>

      <td>
          <a href = "{% url 'main:delete_log_confirm' log.id %}">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg>
          </a>
      </td>
    </tr>
  {%endfor%}
  {%else%}
  <h5>There is nothing to show.</h5>
  {% endif %}
  </tbody>
      </table>
  </div>
</div>
{% endblock %}

templates/main/settings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Settings

{% endblock%}

{% block content %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-gear-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 0 0-5.86 2.929 2.929 0 0 0 0 5.858z"/>
</svg>
        Settings
    </h1>

      <br>
      <br>

      <form action = "{% url 'main:settings' %}" method = "POST">
  {% csrf_token %}


<p class="lead">
<div class="alert alert-light" role="alert">
<div>

Path ||
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-folder-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31L.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3zm-8.322.12C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139z"/>
</svg>

     : {{ form.path }}
</div>
  </div>
    </p>

    <p class="lead">
<div class="alert alert-light" role="alert">
<div>
    Recording ||
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera-reels-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M2.667 6h6.666C10.253 6 11 6.746 11 7.667v6.666c0 .92-.746 1.667-1.667 1.667H2.667C1.747 16 1 15.254 1 14.333V7.667C1 6.747 1.746 6 2.667 6z"/>
  <path d="M7.404 11.697l6.363 3.692c.54.313 1.233-.066 1.233-.697V7.308c0-.63-.693-1.01-1.233-.696l-6.363 3.692a.802.802 0 0 0 0 1.393z"/>
  <circle cx="3" cy="3" r="3"/>
  <circle cx="9" cy="3" r="3"/>
</svg>
    : {{ form.recording }}

</div>
  </div>
    </p>

   <p class="lead">
<div class="alert alert-light" role="alert">
<div>
    Frames per second ||

    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-film" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M0 1a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V1zm4 0h8v6H4V1zm8 8H4v6h8V9zM1 1h2v2H1V1zm2 3H1v2h2V4zM1 7h2v2H1V7zm2 3H1v2h2v-2zm-2 3h2v2H1v-2zM15 1h-2v2h2V1zm-2 3h2v2h-2V4zm2 3h-2v2h2V7zm-2 3h2v2h-2v-2zm2 3h-2v2h2v-2z"/>
</svg>
: {{ form.fps }} frames/sec
</div>
  </div>
    </p>

<button type="Submit" class="btn btn-outline-secondary">
    Save Changes
</button>
</form>



  </div>
</div>

{% endblock %}

templates/main/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!DOCTYPE html>
<html>

   <head>
      <title>Checkbox Control</title>
   </head>

   <body>
      <form>
         <input type = "checkbox" name = "maths" checked aria-checked="false"> Maths
         <input type = "checkbox" name = "physics" value = "on"> Physics
      </form>
   </body>
<a href = "output4.mp4" download>Pull it </a>
</html>
</body>
</html>